-- Migration: 0063_register_ghost_mapped_features.sql
-- Author: resolution-gap sweep, 2026-09-11
-- Applies via: sudo -u postgres psql griddb -f migrations/0063_register_ghost_mapped_features.sql
--
-- Purpose: register nine features that normalization/entity_map.py ALREADY
--          maps raw series_ids onto, but which have no feature_registry row.
--          This is the same failure mode 0062 fixed for GDELT:
--          EntityMap.get_feature_id() looks the mapped name up in
--          feature_registry and returns None when it is absent, logging
--          "Mapping exists (X -> Y) but feature not in registry" — so the
--          resolver silently drops every raw_series observation for them.
--
--          These are "ghost mappings": they do not appear in any count of
--          UNMAPPED series, because a mapping does exist. They look wired and
--          produce nothing, which is why they survived several passes over
--          the resolution gap.
--
--          Verified absent from feature_registry on griddb, 2026-09-11:
--            eurusd_ecb_daily, shy_full, ief_full, emb_full, jnk_full,
--            mub_full, smh_close, icln_close, lit_close
--
--          Where each mapping already lives in entity_map.py:
--            eurusd_ecb_daily  self-mapping, SEED_MAPPINGS
--            smh_close / icln_close / lit_close
--                              SEED_MAPPINGS, "YF:<T>:close"
--            shy/ief/emb/jnk/mub_full
--                              NEW_MAPPINGS_V2, generated by the bond/commodity
--                              ETF comprehension over close and adj_close
--
--          Live evidence these series are being written today: the resolver's
--          own warnings name YF:MUB:adj_close -> mub_full and
--          YF:SHY:adj_close -> shy_full, and eurusd_ecb_daily had 339 rows in
--          the 30 d to 2026-09-11 (newest 2026-09-10) — the largest single
--          item in this migration.
--
-- Deliberately NOT included:
--   oi_k_shape_ratio — a survey of this gap reported ~25,506 rows/30d for it;
--     a direct bounded query returned 0 rows in the 30 d to 2026-09-11.
--     Registering a feature with no writer adds freshness noise, so it is left
--     out until a producer is confirmed.
--   china_*, pboc_*, italy_btp_* — these need a mapping AND a registry row,
--     and their row volumes are not yet verified here. Separate change.
--
-- Populated by: existing scheduled pullers (ECB FX, yfinance ETF closes) via
--               normalization/resolver.py, once these rows exist.
--
-- Idempotent: ON CONFLICT (name) DO NOTHING, matching 0062 and
-- ingestion/seed_v2.py. No new table or sequence, so no GRANT footer is
-- required (grid already has privileges on feature_registry).

-- ====== DATA ======

INSERT INTO feature_registry
  (name, family, description, transformation,
   transformation_version, lag_days, normalization, missing_data_policy,
   eligible_from_date, model_eligible)
VALUES
  -- FX: the largest ghost by row volume (339 rows / 30 d)
  ('eurusd_ecb_daily', 'fx', 'EUR/USD daily reference rate published by the ECB',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE),

  -- Bond ETF closes: mapped by the NEW_MAPPINGS_V2 comprehension over
  -- close and adj_close, target *_full, never registered.
  ('shy_full', 'credit', 'iShares 1-3 Year Treasury Bond ETF (SHY) close',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE),
  ('ief_full', 'credit', 'iShares 7-10 Year Treasury Bond ETF (IEF) close',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE),
  ('emb_full', 'credit', 'iShares JP Morgan USD Emerging Markets Bond ETF (EMB) close',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE),
  ('jnk_full', 'credit', 'SPDR Bloomberg High Yield Bond ETF (JNK) close',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE),
  ('mub_full', 'credit', 'iShares National Muni Bond ETF (MUB) close',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE),

  -- Sector/theme ETF closes: mapped in SEED_MAPPINGS, never registered.
  ('smh_close', 'equity', 'VanEck Semiconductor ETF (SMH) close',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE),
  ('icln_close', 'equity', 'iShares Global Clean Energy ETF (ICLN) close',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE),
  ('lit_close', 'commodity', 'Global X Lithium & Battery Tech ETF (LIT) close',
   'RAW', 1, 0, 'NONE', 'FORWARD_FILL', '2026-01-01', TRUE)
ON CONFLICT (name) DO NOTHING;
