"""Write hermes activity to the Obsidian vault session log.

The vault at /data/grid_obsidian/ is the canonical knowledge graph
across cluster nodes (per the obsidian-reporting rule). Hermes runs
every 4 hours doing trust cycles, autoresearch, intelligence tasks,
and so on — without a write hook, those cycles are invisible in the
operator's session timeline.

This module appends one entry per cycle to a daily session file at
``/data/grid_obsidian/Sessions/hermes-YYYY-MM-DD.md``. The file is
the standard 4-section format (What was done / Non-obvious decisions
/ Broken or TBD / Next pick-up) but each cycle appends a sub-block
rather than starting a new file.

Safe by default — every write is best-effort; failures log at WARN
and never break the daemon.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from loguru import logger as log


VAULT_DIR = Path(os.environ.get(
    "GRID_OBSIDIAN_VAULT",
    "/data/grid_obsidian",
))


def _today_session_path() -> Path:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return VAULT_DIR / "Sessions" / f"hermes-{today}.md"


def _ensure_header(path: Path) -> None:
    if path.exists():
        return
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    header = f"""# Hermes daemon log — {today}

Auto-generated by the GRID hermes operator. One sub-block per cycle.
The vault sync cron picks this up on its next 15-min tick.

"""
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(header, encoding="utf-8")
    except Exception as exc:  # noqa: BLE001
        log.warning("obsidian_log: failed to create {p}: {e}", p=path, e=str(exc))


def append_cycle_entry(
    *,
    cycle_name: str,
    summary: str,
    details: dict[str, Any] | None = None,
    tbd: list[str] | None = None,
) -> bool:
    """Append a hermes cycle entry to today's session file.

    Returns True on success, False on any failure (silent — caller
    shouldn't crash if the vault is unavailable).
    """
    if not VAULT_DIR.exists():
        log.debug("obsidian_log: vault {p} not present; skipping", p=VAULT_DIR)
        return False

    path = _today_session_path()
    _ensure_header(path)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"## {ts} — {cycle_name}",
        "",
        f"What was done:",
        "",
        f"- {summary}",
    ]
    if details:
        for k, v in details.items():
            lines.append(f"- **{k}**: {v}")
    if tbd:
        lines.append("")
        lines.append("Broken or TBD:")
        lines.append("")
        for item in tbd:
            lines.append(f"- {item}")
    lines.append("")
    lines.append("")

    try:
        with path.open("a", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return True
    except Exception as exc:  # noqa: BLE001
        log.warning("obsidian_log: append failed {p}: {e}", p=path, e=str(exc))
        return False


def log_trust_cycle(summary_dict: dict[str, Any]) -> bool:
    """Convenience wrapper for the trust_cycle stage of hermes."""
    n_scored = summary_dict.get("scored", 0)
    n_correct = summary_dict.get("correct", 0)
    n_wrong = summary_dict.get("wrong", 0)
    n_unscoreable = summary_dict.get("unscoreable", 0)
    n_expired = summary_dict.get("expired", 0)
    return append_cycle_entry(
        cycle_name="trust_cycle",
        summary=(
            f"scored {n_scored:,} signals "
            f"(CORRECT={n_correct:,}, WRONG={n_wrong:,}, "
            f"unscoreable={n_unscoreable:,}, expired={n_expired:,})"
        ),
        details={
            "module": "intelligence.trust_scorer.score_pending_signals",
        },
    )


def log_intelligence_task(
    task_name: str,
    result: dict[str, Any] | str,
) -> bool:
    """Generic wrapper for a single intelligence-task slot in hermes."""
    summary = str(result)[:240] if not isinstance(result, dict) else (
        ", ".join(f"{k}={v}" for k, v in list(result.items())[:5])[:240]
    )
    return append_cycle_entry(
        cycle_name=f"intelligence:{task_name}",
        summary=summary,
    )
