"""
Sovereign Wealth Fund Intelligence Network
GRID Trading Intelligence Platform

Covers top 15 SWFs by AUM with actor mapping, holdings,
geopolitical leverage, and confidence labels.

Confidence labels per GRID protocol:
  confirmed  = public filings, official disclosures, audited reports
  derived    = calculated from multiple confirmed sources
  estimated  = reasonable inference from partial data
  rumored    = unverified but reported by credible outlets
  inferred   = pattern-based deduction without direct evidence
"""

SWF_INTELLIGENCE = {
    "metadata": {
        "report_type": "sovereign_wealth_fund_network",
        "version": "1.0.0",
        "generated": "2026-03-28",
        "total_aum_estimated_usd": "8.5T",
        "confidence_schema": [
            "confirmed",
            "derived",
            "estimated",
            "rumored",
            "inferred",
        ],
        "sources": [
            "SWFI Institute",
            "SEC 13F filings",
            "Annual reports",
            "Bloomberg",
            "Reuters",
            "IFSWF",
            "Santiago Principles disclosures",
        ],
    },
    "funds": [
        # ── 1. NORWAY GPFG ──────────────────────────────────────────
        {
            "id": "GPFG",
            "name": "Government Pension Fund Global",
            "country": "Norway",
            "aum_usd": "1.7T",
            "aum_confidence": "confirmed",
            "aum_trend": "up_8pct_2024",
            "established": 1990,
            "key_personnel": [
                {
                    "name": "Nicolai Tangen",
                    "role": "CEO, Norges Bank Investment Management",
                    "since": 2020,
                    "background": "Former AKO Capital hedge fund founder, $15B AUM",
                    "confidence": "confirmed",
                },
                {
                    "name": "Ida Wolden Bache",
                    "role": "Governor, Norges Bank",
                    "since": 2022,
                    "confidence": "confirmed",
                },
                {
                    "name": "Carine Smith Ihenacho",
                    "role": "Chief Governance & Compliance Officer",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Norwegian Ministry of Finance",
                "independence_level": "high",
                "note": "Operates under strict ethical guidelines, parliamentary oversight",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Apple", "value_usd": "~$15B", "confidence": "confirmed"},
                {"company": "Microsoft", "value_usd": "~$14B", "confidence": "confirmed"},
                {"company": "Alphabet", "value_usd": "~$9B", "confidence": "confirmed"},
                {"company": "Amazon", "value_usd": "~$8B", "confidence": "confirmed"},
                {"company": "Meta Platforms", "value_usd": "~$6B", "confidence": "confirmed"},
                {"company": "NVIDIA", "value_usd": "~$7B", "confidence": "confirmed"},
                {"company": "Nestle", "value_usd": "~$6B", "confidence": "confirmed"},
                {"company": "ASML", "value_usd": "~$5B", "confidence": "confirmed"},
                {"company": "Roche", "value_usd": "~$4.5B", "confidence": "confirmed"},
                {"company": "Novo Nordisk", "value_usd": "~$5B", "confidence": "confirmed"},
            ],
            "real_estate_holdings": [
                {"property": "Regent Street portfolio, London", "value_usd": "~$3.5B", "confidence": "confirmed"},
                {"property": "Times Square retail, NYC", "value_usd": "~$1.5B", "confidence": "confirmed"},
                {"property": "Prologis logistics JV, global", "value_usd": "~$2B", "confidence": "confirmed"},
                {"property": "Paris commercial offices", "value_usd": "~$2B", "confidence": "confirmed"},
                {"property": "Berlin residential portfolio", "value_usd": "~$1B", "confidence": "estimated"},
                {"property": "Boston/SF office towers", "value_usd": "~$1.5B", "confidence": "confirmed"},
            ],
            "investment_style": {
                "approach": "passive_index_replicating_with_active_tilt",
                "equity_pct": 72,
                "fixed_income_pct": 25,
                "real_estate_pct": 3,
                "sectors": "broad_market_cap_weighted",
                "exclusions": "tobacco, certain weapons, severe environmental damage, coal >30%",
                "active_ownership": "yes, votes at ~12,000 shareholder meetings/year",
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~46%",
                "value_usd": "~$780B",
                "confidence": "derived",
                "note": "Largest single foreign investor in US equities. Holds ~1.5% of every listed European company, ~2.5% of every listed US company on average.",
            },
            "geopolitical_leverage": {
                "mechanism": "ethical_exclusion_lists",
                "description": "Exclusion/watchlist decisions move markets and shame companies globally. Fund's ethical council sets de facto global ESG standards.",
                "examples": [
                    "Excluded Walmart (2006, labor rights), re-included later",
                    "Excluded Rio Tinto, Barrick Gold (environmental damage)",
                    "Coal divestment moved global institutional norms",
                ],
                "leverage_rating": "medium_soft_power",
                "confidence": "confirmed",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "highest_globally",
                "note": "Full public disclosure of every holding down to individual stock level. Searchable online database. Benchmark for SWF transparency.",
                "confidence": "confirmed",
            },
        },
        # ── 2. CHINA CIC ────────────────────────────────────────────
        {
            "id": "CIC",
            "name": "China Investment Corporation",
            "country": "China",
            "aum_usd": "1.3T",
            "aum_confidence": "estimated",
            "aum_trend": "stable_to_down_post_2022_real_estate_crisis",
            "established": 2007,
            "key_personnel": [
                {
                    "name": "Peng Chun",
                    "role": "Chairman",
                    "since": 2023,
                    "background": "Former chairman of Bank of Communications",
                    "confidence": "confirmed",
                },
                {
                    "name": "Ju Weimin",
                    "role": "President & CIO",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "State Council of PRC (directly)",
                "independence_level": "very_low",
                "note": "Reports directly to State Council. Leadership rotated by CCP. Serves as extension of state economic policy. Xi Jinping has final authority.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Central Huijin (controls Big Four banks)", "value_usd": "~$300B", "confidence": "derived"},
                {"company": "Alibaba Group", "value_usd": "~$8B", "confidence": "estimated"},
                {"company": "Various US tech (via external managers)", "value_usd": "~$15B", "confidence": "estimated"},
                {"company": "Thames Water (UK)", "value_usd": "~$2B", "confidence": "confirmed"},
                {"company": "Heathrow Airport (10% stake)", "value_usd": "~$3B", "confidence": "confirmed"},
                {"company": "Blackstone (LP stakes)", "value_usd": "~$3B", "confidence": "estimated"},
                {"company": "Morgan Stanley (historical)", "value_usd": "~$5B", "confidence": "confirmed"},
                {"company": "Various PE fund commitments", "value_usd": "~$20B", "confidence": "estimated"},
                {"company": "Agricultural Bank of China", "value_usd": "~$15B", "confidence": "derived"},
                {"company": "China Construction Bank", "value_usd": "~$20B", "confidence": "derived"},
            ],
            "real_estate_holdings": [
                {"property": "Logicor European logistics (via Blackstone)", "value_usd": "~$14B", "confidence": "confirmed"},
                {"property": "One New Change, London (partial)", "value_usd": "~$500M", "confidence": "estimated"},
                {"property": "Various US office towers via JVs", "value_usd": "~$3B", "confidence": "estimated"},
                {"property": "Australian commercial property portfolio", "value_usd": "~$2B", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "active_strategic_with_domestic_policy_mandate",
                "equity_pct": 38,
                "fixed_income_pct": 18,
                "alternatives_pct": 44,
                "sectors": "infrastructure, energy, tech, financials",
                "note": "Dual mandate: financial returns AND strategic national interest. Heavy PE/alternatives allocation.",
                "confidence": "derived",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~15-20%",
                "value_usd": "~$200-260B",
                "confidence": "estimated",
                "note": "Declining US exposure post-2018 trade war. Increasingly routed through third-party managers and offshore vehicles. CFIUS scrutiny has pushed activity underground.",
            },
            "geopolitical_leverage": {
                "mechanism": "strategic_investment_as_statecraft",
                "description": "CIC investments serve Belt & Road objectives. Can weaponize capital allocation. Used to gain influence in emerging markets and secure resource access.",
                "examples": [
                    "Heavy investment in African mining and infrastructure",
                    "Strategic stakes in European ports and logistics",
                    "Central Huijin arm used to stabilize Chinese stock market crashes",
                ],
                "leverage_rating": "very_high",
                "confidence": "derived",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "very_low",
                "note": "Minimal public disclosure. No detailed portfolio reporting. Extensive use of offshore subsidiaries, nominee structures, and third-party fund managers to obscure holdings. Central Huijin subsidiary is itself a labyrinth.",
                "known_vehicles": [
                    "CIC International (Hong Kong)",
                    "CIC Capital Corporation",
                    "Central Huijin Investment",
                    "Jianyin Investment (subsidiary)",
                ],
                "confidence": "derived",
            },
        },
        # ── 3. ABU DHABI ADIA ────────────────────────────────────────
        {
            "id": "ADIA",
            "name": "Abu Dhabi Investment Authority",
            "country": "UAE (Abu Dhabi)",
            "aum_usd": "990B",
            "aum_confidence": "estimated",
            "aum_trend": "up_driven_by_oil_and_market_returns",
            "established": 1976,
            "key_personnel": [
                {
                    "name": "Sheikh Tahnoun bin Zayed Al Nahyan",
                    "role": "Chairman (also National Security Adviser)",
                    "since": 2024,
                    "background": "Brother of UAE President MBZ. Controls vast business empire (Royal Group, IHC). Most powerful economic actor in UAE.",
                    "confidence": "confirmed",
                },
                {
                    "name": "Hamed bin Zayed Al Nahyan",
                    "role": "Managing Director (former Chairman)",
                    "confidence": "confirmed",
                },
                {
                    "name": "Sheikh Mohamed bin Zayed (MBZ)",
                    "role": "UAE President, ultimate authority",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Al Nahyan ruling family (direct)",
                "independence_level": "low_family_controlled",
                "note": "ADIA is the Al Nahyan family's primary wealth vehicle. Sheikh Tahnoun's appointment as chairman consolidated royal family control over all Abu Dhabi sovereign vehicles.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "US equity index funds (passive core)", "value_usd": "~$150B", "confidence": "estimated"},
                {"company": "Emerging market equities", "value_usd": "~$80B", "confidence": "estimated"},
                {"company": "European equities (indexed)", "value_usd": "~$70B", "confidence": "estimated"},
                {"company": "Citigroup (historical 4.9% stake)", "value_usd": "~$7.5B at purchase", "confidence": "confirmed"},
                {"company": "Apollo Global Management (LP)", "value_usd": "~$5B", "confidence": "estimated"},
                {"company": "Reliance Industries (India)", "value_usd": "~$2B", "confidence": "rumored"},
                {"company": "Various PE fund commitments", "value_usd": "~$60B", "confidence": "estimated"},
                {"company": "Gatwick Airport stake", "value_usd": "~$3B", "confidence": "confirmed"},
                {"company": "Equinor (Norway)", "value_usd": "~$1.5B", "confidence": "estimated"},
                {"company": "Global infrastructure funds", "value_usd": "~$40B", "confidence": "estimated"},
            ],
            "real_estate_holdings": [
                {"property": "230 Park Avenue, NYC (Helmsley Building)", "value_usd": "~$1.2B", "confidence": "confirmed"},
                {"property": "Broadgate complex, London (partial via BL)", "value_usd": "~$3B", "confidence": "estimated"},
                {"property": "Global logistics/warehouse portfolio", "value_usd": "~$5B", "confidence": "estimated"},
                {"property": "San Francisco/LA office towers", "value_usd": "~$2B", "confidence": "estimated"},
                {"property": "Paris Champs-Elysees properties", "value_usd": "~$1B", "confidence": "rumored"},
            ],
            "investment_style": {
                "approach": "large_passive_core_with_active_satellite",
                "equity_pct": 42,
                "fixed_income_pct": 10,
                "alternatives_pct": 25,
                "real_estate_pct": 8,
                "infrastructure_pct": 8,
                "cash_pct": 7,
                "sectors": "diversified, heavy alternatives",
                "note": "One of the earliest adopters of alternatives and PE co-investment. Uses 20+ external fund managers.",
                "confidence": "derived",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~35-40%",
                "value_usd": "~$350-400B",
                "confidence": "estimated",
                "note": "Massive US exposure through both direct holdings and external managers. Historically US-weighted. Diversifying toward Asia.",
            },
            "geopolitical_leverage": {
                "mechanism": "economic_diplomacy_and_strategic_stakes",
                "description": "ADIA investments cement Abu Dhabi's role as essential global capital provider. Stakes in Western financial infrastructure create mutual dependency.",
                "examples": [
                    "Citigroup bailout stake during 2008 crisis",
                    "Abu Dhabi's financial muscle prevents Western confrontation on human rights",
                    "Gateway to broader Gulf investment flows",
                ],
                "leverage_rating": "high",
                "confidence": "derived",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "low",
                "note": "ADIA discloses almost nothing about specific holdings. Asset allocation bands published annually since 2010 (post-Santiago Principles) but no position-level detail. Extensive use of external managers provides built-in opacity.",
                "confidence": "confirmed",
            },
        },
        # ── 4. KUWAIT KIA ────────────────────────────────────────────
        {
            "id": "KIA",
            "name": "Kuwait Investment Authority",
            "country": "Kuwait",
            "aum_usd": "920B",
            "aum_confidence": "estimated",
            "aum_trend": "up_slowly",
            "established": 1953,
            "key_personnel": [
                {
                    "name": "Ghanem Al-Ghenaiman",
                    "role": "Managing Director",
                    "since": 2023,
                    "confidence": "confirmed",
                },
                {
                    "name": "Bader Al-Saad",
                    "role": "Former MD (2003-2017), longest-serving",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Kuwait Ministry of Finance, Supreme Petroleum Council",
                "independence_level": "medium",
                "note": "World's oldest SWF (1953). Two sub-funds: General Reserve Fund (budget buffer) and Future Generations Fund (intergenerational). Parliamentary oversight but Emir has ultimate authority.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Mercedes-Benz (6.8% stake)", "value_usd": "~$5B", "confidence": "confirmed"},
                {"company": "BP (historical, reduced)", "value_usd": "~$2B", "confidence": "estimated"},
                {"company": "Bank of America (historical)", "value_usd": "~$3B", "confidence": "confirmed"},
                {"company": "Areva/Orano (France nuclear)", "value_usd": "~$1B", "confidence": "estimated"},
                {"company": "US equity index portfolio", "value_usd": "~$80B", "confidence": "estimated"},
                {"company": "European equity portfolio", "value_usd": "~$50B", "confidence": "estimated"},
                {"company": "EM equity portfolio", "value_usd": "~$30B", "confidence": "estimated"},
                {"company": "Industrial & Commercial Bank of China", "value_usd": "~$2B", "confidence": "estimated"},
                {"company": "Various PE fund stakes", "value_usd": "~$25B", "confidence": "estimated"},
                {"company": "Gulf Bank, National Bank of Kuwait", "value_usd": "~$5B", "confidence": "derived"},
            ],
            "real_estate_holdings": [
                {"property": "St Martins Property Group (London, subsidiary)", "value_usd": "~$8B", "confidence": "confirmed"},
                {"property": "One Canada Square (Canary Wharf partial)", "value_usd": "~$1B", "confidence": "estimated"},
                {"property": "US office portfolio via Hines JV", "value_usd": "~$3B", "confidence": "estimated"},
                {"property": "Wren House Infrastructure (subsidiary)", "value_usd": "~$5B", "confidence": "confirmed"},
            ],
            "investment_style": {
                "approach": "conservative_long_term_diversified",
                "equity_pct": 50,
                "fixed_income_pct": 20,
                "alternatives_pct": 20,
                "real_estate_pct": 10,
                "sectors": "broad diversification, infrastructure, real estate",
                "note": "Oldest SWF. Generally conservative. Heavy London real estate. Long-standing relationships with Western managers.",
                "confidence": "derived",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~30%",
                "value_usd": "~$275B",
                "confidence": "estimated",
            },
            "geopolitical_leverage": {
                "mechanism": "strategic_alliances_through_investment",
                "description": "KIA investments in Western blue chips cement the US-Kuwait defense relationship. Gulf War liberation of Kuwait created permanent alliance.",
                "leverage_rating": "medium",
                "confidence": "derived",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "low",
                "note": "Very limited public disclosure. St Martins Property Group and Wren House Infrastructure are wholly-owned operating subsidiaries. AUM figures are unofficial estimates.",
                "confidence": "confirmed",
            },
        },
        # ── 5. SAUDI PIF ─────────────────────────────────────────────
        {
            "id": "PIF",
            "name": "Public Investment Fund",
            "country": "Saudi Arabia",
            "aum_usd": "930B",
            "aum_confidence": "estimated",
            "aum_trend": "up_rapidly_vision_2030_inflows",
            "established": 1971,
            "key_personnel": [
                {
                    "name": "Mohammed bin Salman (MBS)",
                    "role": "Chairman, Crown Prince of Saudi Arabia",
                    "since": 2015,
                    "background": "De facto ruler of Saudi Arabia. PIF is his primary vehicle for Vision 2030 economic transformation.",
                    "confidence": "confirmed",
                },
                {
                    "name": "Yasir Al-Rumayyan",
                    "role": "Governor (CEO equivalent)",
                    "since": 2015,
                    "background": "Former Saudi Fransi Capital CEO. Also chairman of Aramco, Newcastle United, LIV Golf parent.",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "MBS directly, no independent board",
                "independence_level": "none_one_man_vehicle",
                "note": "PIF is MBS's personal economic transformation tool. No separation between state interest and PIF strategy. Completely directed by Crown Prince.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Saudi Aramco (8% stake)", "value_usd": "~$160B", "confidence": "confirmed"},
                {"company": "STC (Saudi Telecom, 64% stake)", "value_usd": "~$30B", "confidence": "confirmed"},
                {"company": "SABIC (70% stake via Aramco deal)", "value_usd": "~$20B", "confidence": "confirmed"},
                {"company": "Lucid Motors (>60% stake)", "value_usd": "~$4B", "confidence": "confirmed"},
                {"company": "Nintendo (8.6% stake)", "value_usd": "~$7B", "confidence": "confirmed"},
                {"company": "Electronic Arts (large stake)", "value_usd": "~$3B", "confidence": "confirmed"},
                {"company": "Activision Blizzard (sold to MSFT)", "value_usd": "~$3.5B at sale", "confidence": "confirmed"},
                {"company": "SoftBank Vision Fund (LP $45B)", "value_usd": "~$45B committed", "confidence": "confirmed"},
                {"company": "Uber (historical, partially sold)", "value_usd": "~$3.5B", "confidence": "confirmed"},
                {"company": "Jio Platforms (India)", "value_usd": "~$1.5B", "confidence": "confirmed"},
            ],
            "real_estate_holdings": [
                {"property": "NEOM ($500B megacity project)", "value_usd": "~$500B planned, ~$30B spent", "confidence": "estimated"},
                {"property": "The LINE (170km linear city at NEOM)", "value_usd": "~$200B planned", "confidence": "confirmed"},
                {"property": "ROSHN (Saudi residential developer)", "value_usd": "~$10B portfolio", "confidence": "estimated"},
                {"property": "Red Sea Global (luxury tourism)", "value_usd": "~$10B", "confidence": "estimated"},
                {"property": "King Abdullah Financial District, Riyadh", "value_usd": "~$8B", "confidence": "estimated"},
                {"property": "Savoy Hotel, London (via Accor)", "value_usd": "~$1B", "confidence": "rumored"},
            ],
            "investment_style": {
                "approach": "aggressive_active_transformation_vehicle",
                "domestic_pct": 60,
                "international_pct": 40,
                "sectors": "gaming, sports, tech, mega-infrastructure, tourism, EV",
                "note": "PIF is NOT a traditional SWF. It is an economic transformation vehicle for Vision 2030. Takes large concentrated bets. Heavy sports/entertainment strategy (LIV Golf, Newcastle United, WWE/UFC, esports).",
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~15-20%",
                "value_usd": "~$140-185B",
                "confidence": "estimated",
                "note": "Growing US tech/gaming exposure. Significant via SoftBank Vision Fund. Direct stakes in Lucid, gaming companies. Likely additional undisclosed positions.",
            },
            "geopolitical_leverage": {
                "mechanism": "investment_as_geopolitical_currency",
                "description": "PIF investments buy geopolitical cover for MBS. Sportswashing via Newcastle, LIV Golf, WWE. Tech investments create Silicon Valley dependency. Aramco IPO was geopolitical event.",
                "examples": [
                    "Khashoggi murder: PIF investments continued, Western capital kept flowing",
                    "LIV Golf / Newcastle United as sportswashing vehicles",
                    "SoftBank Vision Fund gave MBS tech sector influence",
                    "Used PIF to threaten economic consequences against critics",
                    "Aramco IPO valuation as national prestige project",
                ],
                "leverage_rating": "very_high",
                "confidence": "confirmed",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "very_low",
                "note": "PIF publishes limited annual report. No position-level disclosure for international portfolio. Extensive use of subsidiaries (SRJ Sports, Savvy Gaming). Giga-projects are PIF subsidiaries with independent boards but no real independence.",
                "known_vehicles": [
                    "Sanabil Investments (VC/PE arm)",
                    "Savvy Gaming Group",
                    "SRJ Sports Investments",
                    "NEOM Company",
                    "ROSHN Group",
                    "Red Sea Global",
                    "Qiddiya Investment Company",
                ],
                "confidence": "derived",
            },
        },
        # ── 6. GIC SINGAPORE ─────────────────────────────────────────
        {
            "id": "GIC",
            "name": "GIC Private Limited",
            "country": "Singapore",
            "aum_usd": "770B",
            "aum_confidence": "estimated",
            "aum_trend": "up_steadily",
            "established": 1981,
            "key_personnel": [
                {
                    "name": "Lee Hsien Loong",
                    "role": "Chairman (former PM)",
                    "since": 2024,
                    "background": "Former PM of Singapore (2004-2024). Son of Lee Kuan Yew (GIC founder). Transition from PM to chairman maintains Lee family oversight.",
                    "confidence": "confirmed",
                },
                {
                    "name": "Lim Chow Kiat",
                    "role": "CEO",
                    "since": 2017,
                    "confidence": "confirmed",
                },
                {
                    "name": "Jeffrey Jaensubhakij",
                    "role": "President, Group CIO",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Singapore government, President has custodial role",
                "independence_level": "medium_lee_family_legacy",
                "note": "Founded by Lee Kuan Yew. Lee Hsien Loong became chairman after stepping down as PM. Lee family maintains extraordinary influence over both GIC and Temasek (wife Ho Ching led Temasek).",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Global equity index portfolio", "value_usd": "~$200B", "confidence": "estimated"},
                {"company": "UBS (post-Credit Suisse merger)", "value_usd": "~$5B", "confidence": "confirmed"},
                {"company": "Bharti Airtel (India)", "value_usd": "~$3B", "confidence": "confirmed"},
                {"company": "Various Chinese tech (reduced)", "value_usd": "~$10B", "confidence": "estimated"},
                {"company": "Global PE fund commitments", "value_usd": "~$60B", "confidence": "estimated"},
                {"company": "Equinix", "value_usd": "~$2B", "confidence": "estimated"},
                {"company": "Real estate-related equities", "value_usd": "~$15B", "confidence": "estimated"},
                {"company": "Infrastructure fund stakes", "value_usd": "~$30B", "confidence": "estimated"},
                {"company": "KKR, Blackstone LP stakes", "value_usd": "~$5B", "confidence": "estimated"},
                {"company": "Southeast Asian banks and telcos", "value_usd": "~$8B", "confidence": "estimated"},
            ],
            "real_estate_holdings": [
                {"property": "Global Logistic Properties (divested but reinvested)", "value_usd": "~$5B", "confidence": "estimated"},
                {"property": "Student housing portfolio (US/UK)", "value_usd": "~$3B", "confidence": "estimated"},
                {"property": "NYC office towers", "value_usd": "~$4B", "confidence": "estimated"},
                {"property": "London West End commercial", "value_usd": "~$3B", "confidence": "estimated"},
                {"property": "Tokyo/Osaka commercial", "value_usd": "~$2B", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "active_global_diversified",
                "equity_pct": 32,
                "fixed_income_pct": 17,
                "real_estate_pct": 13,
                "pe_infra_pct": 23,
                "absolute_return_pct": 15,
                "sectors": "global diversification, real estate, infrastructure, private equity",
                "note": "Known for 20-year rolling return benchmark. Risk-adjusted approach. Strong PE and co-investment program.",
                "confidence": "derived",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~34%",
                "value_usd": "~$260B",
                "confidence": "estimated",
            },
            "geopolitical_leverage": {
                "mechanism": "neutral_hub_capital_diplomacy",
                "description": "Singapore positions itself as neutral broker between US and China. GIC investments in both demonstrate this balance. Fund legitimizes Singapore's outsized global influence.",
                "leverage_rating": "medium",
                "confidence": "derived",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "medium_low",
                "note": "Publishes annual report with asset allocation and performance, but no position-level detail. Does not disclose AUM (officially). Figures are SWFI/market estimates.",
                "confidence": "confirmed",
            },
        },
        # ── 7. HKMA ──────────────────────────────────────────────────
        {
            "id": "HKMA_EF",
            "name": "Hong Kong Monetary Authority Exchange Fund",
            "country": "Hong Kong SAR (China)",
            "aum_usd": "580B",
            "aum_confidence": "confirmed",
            "aum_trend": "up_from_2023_lows",
            "established": 1935,
            "key_personnel": [
                {
                    "name": "Eddie Yue",
                    "role": "Chief Executive, HKMA",
                    "since": 2019,
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Hong Kong SAR Financial Secretary, ultimately Beijing",
                "independence_level": "medium_eroding_post_2020",
                "note": "Post-National Security Law (2020), Beijing's influence over HKMA policy has increased. Exchange Fund's primary purpose is currency peg defense (HKD-USD).",
                "confidence": "derived",
            },
            "top_equity_holdings": [
                {"company": "Hang Seng Index constituents (from 1998 intervention)", "value_usd": "~$50B", "confidence": "derived"},
                {"company": "US Treasury bonds", "value_usd": "~$200B", "confidence": "estimated"},
                {"company": "US agency bonds (MBS)", "value_usd": "~$50B", "confidence": "estimated"},
                {"company": "Global equity portfolio", "value_usd": "~$80B", "confidence": "estimated"},
                {"company": "HSBC Holdings", "value_usd": "~$5B", "confidence": "derived"},
                {"company": "AIA Group", "value_usd": "~$3B", "confidence": "derived"},
                {"company": "Tencent Holdings", "value_usd": "~$4B", "confidence": "derived"},
                {"company": "China Construction Bank", "value_usd": "~$3B", "confidence": "derived"},
                {"company": "Various global fixed income", "value_usd": "~$150B", "confidence": "estimated"},
                {"company": "Long-Term Growth Portfolio (PE/alternatives)", "value_usd": "~$40B", "confidence": "confirmed"},
            ],
            "real_estate_holdings": [
                {"property": "IFC complex, Hong Kong (partial)", "value_usd": "~$2B", "confidence": "estimated"},
                {"property": "Global real estate fund portfolio", "value_usd": "~$10B", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "currency_peg_defense_first_then_investment",
                "backing_portfolio_pct": 65,
                "investment_portfolio_pct": 25,
                "long_term_growth_pct": 10,
                "note": "Primary mandate is maintaining HKD-USD peg. Investment returns secondary. Conservative by necessity.",
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~50-60%",
                "value_usd": "~$300-350B",
                "confidence": "derived",
                "note": "Extremely high US exposure due to USD peg requirement. Holds massive US Treasuries for peg defense.",
            },
            "geopolitical_leverage": {
                "mechanism": "peg_defense_mutual_dependency",
                "description": "HKMA's $200B+ in US Treasuries creates mutual dependency. Dumping UST would hurt both sides. HK's role as China's capital markets gateway gives Exchange Fund strategic importance.",
                "leverage_rating": "medium_high",
                "confidence": "derived",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "medium",
                "note": "Publishes quarterly results and asset allocation. Does not disclose individual holdings. Long-Term Growth Portfolio is particularly opaque.",
                "confidence": "confirmed",
            },
        },
        # ── 8. TEMASEK SINGAPORE ─────────────────────────────────────
        {
            "id": "TEMASEK",
            "name": "Temasek Holdings",
            "country": "Singapore",
            "aum_usd": "380B",
            "aum_confidence": "confirmed",
            "aum_trend": "stable_post_ftx_loss",
            "established": 1974,
            "key_personnel": [
                {
                    "name": "Dilhan Pillay Sandrasegara",
                    "role": "CEO",
                    "since": 2021,
                    "confidence": "confirmed",
                },
                {
                    "name": "Ho Ching",
                    "role": "Former CEO (2004-2021)",
                    "background": "Wife of Lee Hsien Loong (Singapore PM 2004-2024). Her tenure was controversial due to family-state overlap.",
                    "confidence": "confirmed",
                },
                {
                    "name": "Lim Boon Heng",
                    "role": "Chairman",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Singapore Ministry of Finance (sole shareholder)",
                "independence_level": "medium_lee_family_adjacent",
                "note": "Ho Ching (Lee Hsien Loong's wife) ran Temasek for 17 years. Creates unique Lee family dual-SWF control (GIC chairman + Temasek CEO spouse). Formally independent but politically connected.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "DBS Group (29% stake)", "value_usd": "~$25B", "confidence": "confirmed"},
                {"company": "Singapore Airlines (55% stake)", "value_usd": "~$8B", "confidence": "confirmed"},
                {"company": "Singtel (52% stake)", "value_usd": "~$15B", "confidence": "confirmed"},
                {"company": "Standard Chartered Bank (16%)", "value_usd": "~$4B", "confidence": "confirmed"},
                {"company": "Sea Limited (SE Asia tech)", "value_usd": "~$3B", "confidence": "confirmed"},
                {"company": "Adyen NV", "value_usd": "~$2B", "confidence": "estimated"},
                {"company": "Alibaba (reduced)", "value_usd": "~$2B", "confidence": "estimated"},
                {"company": "Block Inc", "value_usd": "~$1B", "confidence": "estimated"},
                {"company": "Roblox", "value_usd": "~$1B", "confidence": "estimated"},
                {"company": "Various biotech portfolio", "value_usd": "~$8B", "confidence": "estimated"},
            ],
            "real_estate_holdings": [
                {"property": "Mapletree Investments (wholly-owned, global RE)", "value_usd": "~$80B AUM under Mapletree", "confidence": "confirmed"},
                {"property": "CapitaLand Investment (major shareholder)", "value_usd": "~$10B", "confidence": "confirmed"},
                {"property": "Global data center portfolio via Mapletree", "value_usd": "~$5B", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "active_concentrated_growth_oriented",
                "singapore_pct": 28,
                "china_pct": 22,
                "americas_pct": 22,
                "rest_of_asia_pct": 15,
                "europe_pct": 13,
                "sectors": "financials, tech, consumer, life_sciences, industrials",
                "note": "More active and concentrated than GIC. Took $275M loss on FTX collapse (2022). Known for tech bets that sometimes go wrong.",
                "ftx_loss": {"amount": "$275M", "confidence": "confirmed"},
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~22%",
                "value_usd": "~$84B",
                "confidence": "confirmed",
            },
            "geopolitical_leverage": {
                "mechanism": "bridge_capital_between_east_and_west",
                "description": "Temasek operates as a commercial bridge between Asian and Western markets. Less geopolitical than GIC. More focused on commercial returns.",
                "leverage_rating": "low_to_medium",
                "confidence": "derived",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "medium_high",
                "note": "Publishes detailed annual review with major holdings disclosed. More transparent than most Asian SWFs. Still uses subsidiary structures (Mapletree, Vertex, Pavilion Capital).",
                "known_vehicles": [
                    "Mapletree Investments",
                    "Vertex Holdings (VC)",
                    "Pavilion Capital (PE)",
                    "Seviora Holdings",
                    "65 Equity Partners",
                ],
                "confidence": "confirmed",
            },
        },
        # ── 9. QATAR QIA ─────────────────────────────────────────────
        {
            "id": "QIA",
            "name": "Qatar Investment Authority",
            "country": "Qatar",
            "aum_usd": "510B",
            "aum_confidence": "estimated",
            "aum_trend": "up_post_world_cup_spending",
            "established": 2005,
            "key_personnel": [
                {
                    "name": "Sheikh Mohammed bin Abdulrahman Al Thani",
                    "role": "Chairman (also Prime Minister & Foreign Minister)",
                    "since": 2023,
                    "confidence": "confirmed",
                },
                {
                    "name": "Mansoor Al-Mahmoud",
                    "role": "CEO",
                    "since": 2018,
                    "confidence": "confirmed",
                },
                {
                    "name": "Sheikh Tamim bin Hamad Al Thani",
                    "role": "Emir, ultimate authority",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Al Thani ruling family (direct)",
                "independence_level": "very_low_family_vehicle",
                "note": "QIA is the Al Thani family's primary international investment vehicle. Chairman is simultaneously PM and Foreign Minister - no pretense of separation.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Volkswagen (17% stake)", "value_usd": "~$15B", "confidence": "confirmed"},
                {"company": "Credit Suisse (pre-UBS merger, lost most)", "value_usd": "~$1B remaining", "confidence": "derived"},
                {"company": "Barclays (~5% stake)", "value_usd": "~$2B", "confidence": "confirmed"},
                {"company": "Glencore (8.7% stake)", "value_usd": "~$5B", "confidence": "confirmed"},
                {"company": "Rosneft (19.5% stake)", "value_usd": "~$7B", "confidence": "confirmed"},
                {"company": "London Stock Exchange Group (~5%)", "value_usd": "~$3B", "confidence": "confirmed"},
                {"company": "Iberdrola (Spain, 8.7%)", "value_usd": "~$6B", "confidence": "confirmed"},
                {"company": "Porsche AG (stake via VW)", "value_usd": "~$4B", "confidence": "derived"},
                {"company": "Sainsbury's (historical)", "value_usd": "~$1B", "confidence": "estimated"},
                {"company": "Tiffany (sold to LVMH)", "value_usd": "sold", "confidence": "confirmed"},
            ],
            "real_estate_holdings": [
                {"property": "The Shard, London (95% stake)", "value_usd": "~$1.5B", "confidence": "confirmed"},
                {"property": "Harrods department store, London", "value_usd": "~$3B", "confidence": "confirmed"},
                {"property": "One Hyde Park, London", "value_usd": "~$1B", "confidence": "confirmed"},
                {"property": "Canary Wharf Group (majority)", "value_usd": "~$4B", "confidence": "confirmed"},
                {"property": "Chelsea Barracks, London", "value_usd": "~$2B", "confidence": "confirmed"},
                {"property": "US real estate portfolio (NYC, DC)", "value_usd": "~$5B", "confidence": "estimated"},
                {"property": "Valentino fashion house", "value_usd": "~$2B", "confidence": "confirmed"},
                {"property": "Paris Saint-Germain (via QSI)", "value_usd": "~$4B", "confidence": "confirmed"},
            ],
            "investment_style": {
                "approach": "active_trophy_asset_collector",
                "equity_pct": 50,
                "real_estate_pct": 20,
                "alternatives_pct": 20,
                "fixed_income_pct": 10,
                "sectors": "luxury brands, real estate, energy, banking, sports",
                "note": "Known for buying iconic trophy assets (Harrods, The Shard, PSG, VW). Heavy London concentration. Sportswashing via PSG and World Cup hosting.",
                "confidence": "derived",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~20%",
                "value_usd": "~$100B",
                "confidence": "estimated",
                "note": "Lower US exposure than peers. Heavily weighted to London/Europe. Growing US presence.",
            },
            "geopolitical_leverage": {
                "mechanism": "trophy_asset_diplomacy_and_media",
                "description": "QIA's trophy asset strategy buys Qatar influence disproportionate to its 300K citizen population. Al Jazeera + investment portfolio = outsized soft power. Survived Saudi/UAE blockade (2017-2021) using economic leverage.",
                "examples": [
                    "2022 World Cup as national legitimacy project",
                    "PSG ownership as soft power",
                    "Rosneft stake demonstrates Russia relationship",
                    "Al Jazeera network as geopolitical tool",
                    "Mediation role (Taliban, Gaza) backed by economic power",
                ],
                "leverage_rating": "high",
                "confidence": "confirmed",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "very_low",
                "note": "No annual report. No public disclosure of portfolio. Major stakes known only through regulatory filings in investee countries. Qatar Sports Investments (QSI), Katara Hospitality are subsidiaries.",
                "known_vehicles": [
                    "Qatar Sports Investments (QSI)",
                    "Katara Hospitality",
                    "Qatar Holding",
                    "Hassad Food Company",
                    "Qatari Diar Real Estate",
                ],
                "confidence": "derived",
            },
        },
        # ── 10. UAE MUBADALA ─────────────────────────────────────────
        {
            "id": "MUBADALA",
            "name": "Mubadala Investment Company",
            "country": "UAE (Abu Dhabi)",
            "aum_usd": "300B",
            "aum_confidence": "confirmed",
            "aum_trend": "up_rapidly",
            "established": 2002,
            "key_personnel": [
                {
                    "name": "Khaldoon Khalifa Al Mubarak",
                    "role": "Group CEO and Managing Director",
                    "since": 2002,
                    "background": "Also chairman of Manchester City Football Club and City Football Group. Close confidant of MBZ. One of Abu Dhabi's most powerful non-royal figures.",
                    "confidence": "confirmed",
                },
                {
                    "name": "Sheikh Mohamed bin Zayed (MBZ)",
                    "role": "UAE President, chairman of board",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Abu Dhabi government, MBZ directly",
                "independence_level": "low",
                "note": "Merged with IPIC and Abu Dhabi Financial Group in 2017. Khaldoon Al Mubarak is MBZ's right-hand man. Mubadala is Abu Dhabi's strategic/active investment arm vs ADIA's passive approach.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "CEPSA (Spanish energy, 100%)", "value_usd": "~$12B", "confidence": "confirmed"},
                {"company": "GlobalFoundries (88% stake, post-IPO)", "value_usd": "~$8B", "confidence": "confirmed"},
                {"company": "AMD (large historical position, reduced)", "value_usd": "~$3B", "confidence": "estimated"},
                {"company": "Silver Lake Partners (LP/GP stake)", "value_usd": "~$5B", "confidence": "estimated"},
                {"company": "Fortress Investment Group", "value_usd": "~$2B", "confidence": "confirmed"},
                {"company": "Various PE fund stakes (Apollo, KKR)", "value_usd": "~$15B", "confidence": "estimated"},
                {"company": "Strata Manufacturing (100%)", "value_usd": "~$1B", "confidence": "confirmed"},
                {"company": "Masdar (clean energy, 100%)", "value_usd": "~$5B", "confidence": "confirmed"},
                {"company": "Cleveland Clinic Abu Dhabi (JV)", "value_usd": "~$2B", "confidence": "estimated"},
                {"company": "G42 (AI company, Abu Dhabi)", "value_usd": "~$3B", "confidence": "estimated"},
            ],
            "real_estate_holdings": [
                {"property": "Yas Island development (Abu Dhabi)", "value_usd": "~$5B", "confidence": "estimated"},
                {"property": "Saadiyat Island cultural district", "value_usd": "~$3B", "confidence": "estimated"},
                {"property": "Various global real estate via funds", "value_usd": "~$8B", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "active_strategic_industry_builder",
                "sectors": "semiconductors, aerospace, energy, tech, healthcare, AI",
                "note": "Unlike ADIA (passive) or QIA (trophy assets), Mubadala builds industries. GlobalFoundries, Masdar, and aerospace manufacturing are examples of building capabilities, not just deploying capital.",
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~25-30%",
                "value_usd": "~$75-90B",
                "confidence": "estimated",
                "note": "Heavy US exposure through tech (GlobalFoundries, AMD legacy) and PE fund LP stakes. Growing AI sector exposure via G42-Microsoft partnership.",
            },
            "geopolitical_leverage": {
                "mechanism": "strategic_industry_creation",
                "description": "Mubadala creates strategic industries that make Abu Dhabi indispensable. GlobalFoundries = semiconductor leverage. Masdar = clean energy credibility. G42 = AI influence.",
                "examples": [
                    "GlobalFoundries semiconductor fab gives chip supply chain leverage",
                    "Masdar positions UAE as clean energy leader despite being petro-state",
                    "G42 AI partnership with Microsoft gives AI geopolitical positioning",
                    "Manchester City / City Football Group as sportswashing",
                ],
                "leverage_rating": "high",
                "confidence": "derived",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "medium",
                "note": "Publishes annual review with key holdings. More transparent than ADIA. Absorbed IPIC (which was linked to 1MDB scandal). 1MDB-related investigations revealed some previously hidden structures.",
                "1mdb_connection": "IPIC (merged into Mubadala 2017) was used in 1MDB fraud. Abu Dhabi settled for ~$3.5B. Former IPIC MD Khadem Al Qubaisi imprisoned.",
                "confidence": "confirmed",
            },
        },
        # ── 11. AUSTRALIAN FUTURE FUND ───────────────────────────────
        {
            "id": "AFF",
            "name": "Australian Future Fund",
            "country": "Australia",
            "aum_usd": "170B",
            "aum_confidence": "confirmed",
            "aum_trend": "up_steadily",
            "established": 2006,
            "key_personnel": [
                {
                    "name": "Raphael Arndt",
                    "role": "CEO",
                    "since": 2020,
                    "confidence": "confirmed",
                },
                {
                    "name": "Greg Combet",
                    "role": "Chairman",
                    "since": 2020,
                    "background": "Former Labor minister and union leader",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Australian Government (Board of Guardians)",
                "independence_level": "high",
                "note": "Established to cover future public sector pension liabilities. Cannot be drawn upon until 2028. Board appointed by government but operationally independent.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Australian equity portfolio", "value_usd": "~$15B", "confidence": "confirmed"},
                {"company": "Global equity portfolio", "value_usd": "~$40B", "confidence": "confirmed"},
                {"company": "PE fund portfolio", "value_usd": "~$20B", "confidence": "confirmed"},
                {"company": "BHP Group", "value_usd": "~$1.5B", "confidence": "estimated"},
                {"company": "CSL Limited", "value_usd": "~$1.2B", "confidence": "estimated"},
                {"company": "Commonwealth Bank", "value_usd": "~$1B", "confidence": "estimated"},
                {"company": "US tech (via index)", "value_usd": "~$10B", "confidence": "estimated"},
                {"company": "Infrastructure funds", "value_usd": "~$15B", "confidence": "confirmed"},
                {"company": "Hedge fund portfolio", "value_usd": "~$8B", "confidence": "estimated"},
                {"company": "Credit/debt portfolio", "value_usd": "~$10B", "confidence": "confirmed"},
            ],
            "real_estate_holdings": [
                {"property": "Global real estate fund portfolio", "value_usd": "~$8B", "confidence": "confirmed"},
                {"property": "Australian commercial property", "value_usd": "~$3B", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "diversified_total_return",
                "target_return": "CPI + 4-5% per annum",
                "sectors": "broadly diversified, significant alternatives",
                "note": "Benchmark-unaware approach. Significant allocation to alternatives, PE, infrastructure. Draw-down date of 2028 approaching.",
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~30%",
                "value_usd": "~$50B",
                "confidence": "estimated",
            },
            "geopolitical_leverage": {
                "mechanism": "minimal",
                "description": "Purely financial mandate. No geopolitical role. Australia's geopolitical leverage comes from other channels (Five Eyes, AUKUS, resources).",
                "leverage_rating": "none",
                "confidence": "confirmed",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "high",
                "note": "Publishes detailed portfolio composition, asset allocation, and returns. Among the most transparent SWFs globally. Follows Australian public sector transparency standards.",
                "confidence": "confirmed",
            },
        },
        # ── 12. RUSSIA NWF ───────────────────────────────────────────
        {
            "id": "NWF_RUS",
            "name": "National Wealth Fund (Russia)",
            "country": "Russia",
            "aum_usd": "150B",
            "aum_confidence": "estimated",
            "aum_trend": "declining_sanctioned_depleting",
            "established": 2008,
            "key_personnel": [
                {
                    "name": "Anton Siluanov",
                    "role": "Finance Minister, fund overseer",
                    "confidence": "confirmed",
                },
                {
                    "name": "Vladimir Putin",
                    "role": "President, ultimate authority",
                    "confidence": "confirmed",
                },
                {
                    "name": "Elvira Nabiullina",
                    "role": "Central Bank Governor (manages reserves)",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Russian Ministry of Finance, Putin directly",
                "independence_level": "none",
                "note": "NWF is war chest. Being depleted to fund Ukraine war budget deficits. Former separate Reserve Fund merged in 2018. Central bank reserves ($300B+) frozen by Western sanctions.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Sberbank (large stake)", "value_usd": "~$15B pre-sanctions", "confidence": "estimated"},
                {"company": "Aeroflot", "value_usd": "~$1B", "confidence": "estimated"},
                {"company": "Russian Railways bonds", "value_usd": "~$5B", "confidence": "estimated"},
                {"company": "Gazprom (infrastructure bonds)", "value_usd": "~$3B", "confidence": "estimated"},
                {"company": "DOM.RF (housing bonds)", "value_usd": "~$5B", "confidence": "estimated"},
                {"company": "Gold reserves (shifted from USD)", "value_usd": "~$20B", "confidence": "estimated"},
                {"company": "Chinese yuan reserves", "value_usd": "~$15B", "confidence": "estimated"},
                {"company": "Various Russian domestic bonds", "value_usd": "~$30B", "confidence": "estimated"},
                {"company": "Nuclear energy stakes (Rosatom related)", "value_usd": "~$5B", "confidence": "inferred"},
                {"company": "VEB.RF development bank bonds", "value_usd": "~$5B", "confidence": "estimated"},
            ],
            "real_estate_holdings": [
                {"property": "Minimal direct - mostly through state banks", "value_usd": "unknown", "confidence": "inferred"},
            ],
            "investment_style": {
                "approach": "war_chest_and_budget_stabilizer",
                "note": "Fundamentally transformed by sanctions. Pre-2022 held Western sovereign bonds and reserve currencies. Now forced into domestic assets, gold, CNY. Being drawn down to cover budget deficits from war spending.",
                "pre_2022": "Western sovereign bonds, USD, EUR",
                "post_2022": "gold, CNY, domestic bonds, budget drawdowns",
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "0%",
                "value_usd": "$0 (frozen/divested)",
                "confidence": "confirmed",
                "note": "All Western assets frozen. $300B+ in central bank reserves frozen by US/EU/UK/Japan. NWF eliminated USD exposure before invasion.",
            },
            "geopolitical_leverage": {
                "mechanism": "frozen_asset_standoff",
                "description": "Russia's frozen reserves ($300B+) are the subject of the largest asset seizure debate in history. G7 debating using frozen assets for Ukraine reconstruction. Russia threatens retaliation against Western assets in Russia.",
                "examples": [
                    "$300B+ frozen central bank reserves",
                    "Interest ($3-5B/yr) being channeled to Ukraine",
                    "Threat of precedent deterring other nations from holding Western reserves",
                    "China, India, Saudi reducing USD reserves in response",
                ],
                "leverage_rating": "high_as_cautionary_tale",
                "confidence": "confirmed",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "none_post_sanctions",
                "note": "All transparency collapsed post-2022 invasion. No public reporting. Fund being used as opaque budget supplement. Pre-invasion, was moderately transparent.",
                "confidence": "confirmed",
            },
        },
        # ── 13. SOUTH KOREA KIC ──────────────────────────────────────
        {
            "id": "KIC",
            "name": "Korea Investment Corporation",
            "country": "South Korea",
            "aum_usd": "200B",
            "aum_confidence": "confirmed",
            "aum_trend": "up_steadily",
            "established": 2005,
            "key_personnel": [
                {
                    "name": "Jin Seoungho",
                    "role": "CEO & CIO",
                    "since": 2022,
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "National Assembly, Ministry of Strategy & Finance, Bank of Korea",
                "independence_level": "medium_high",
                "note": "Board includes government and private sector. More independent than most Asian SWFs. Funded by Bank of Korea reserves transfer and government contributions.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Global equity index portfolio", "value_usd": "~$80B", "confidence": "confirmed"},
                {"company": "US equity portfolio", "value_usd": "~$50B", "confidence": "estimated"},
                {"company": "European equity portfolio", "value_usd": "~$20B", "confidence": "estimated"},
                {"company": "EM equity portfolio", "value_usd": "~$10B", "confidence": "estimated"},
                {"company": "Global fixed income", "value_usd": "~$50B", "confidence": "estimated"},
                {"company": "PE fund commitments", "value_usd": "~$15B", "confidence": "estimated"},
                {"company": "Infrastructure investments", "value_usd": "~$10B", "confidence": "estimated"},
                {"company": "Hedge fund allocations", "value_usd": "~$5B", "confidence": "estimated"},
                {"company": "Real estate funds", "value_usd": "~$10B", "confidence": "estimated"},
                {"company": "Korean equity (small allocation)", "value_usd": "~$5B", "confidence": "estimated"},
            ],
            "real_estate_holdings": [
                {"property": "US office/multifamily portfolio", "value_usd": "~$3B", "confidence": "estimated"},
                {"property": "European commercial property", "value_usd": "~$2B", "confidence": "estimated"},
                {"property": "Australian real estate", "value_usd": "~$1B", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "diversified_institutional",
                "equity_pct": 42,
                "fixed_income_pct": 30,
                "alternatives_pct": 18,
                "real_estate_pct": 10,
                "note": "Modeled on Norwegian/Canadian pension fund approach. Growing alternatives allocation. Conservative by Asian SWF standards.",
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~35%",
                "value_usd": "~$70B",
                "confidence": "estimated",
            },
            "geopolitical_leverage": {
                "mechanism": "minimal_financial_diplomacy",
                "description": "KIC has no significant geopolitical role. South Korea's security depends on US alliance. KIC investments follow financial logic.",
                "leverage_rating": "none",
                "confidence": "confirmed",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "high",
                "note": "Annual report with detailed asset allocation and performance. Subject to Korean National Assembly audit. Among more transparent SWFs.",
                "confidence": "confirmed",
            },
        },
        # ── 14. TURKEY TWF ───────────────────────────────────────────
        {
            "id": "TWF",
            "name": "Turkey Wealth Fund",
            "country": "Turkey",
            "aum_usd": "90B",
            "aum_confidence": "estimated",
            "aum_trend": "uncertain_lira_devaluation_impact",
            "established": 2016,
            "key_personnel": [
                {
                    "name": "Arda Ermut",
                    "role": "CEO",
                    "since": 2020,
                    "confidence": "confirmed",
                },
                {
                    "name": "Recep Tayyip Erdogan",
                    "role": "Chairman of the board (President of Turkey)",
                    "since": 2018,
                    "background": "Erdogan personally chairs TWF board. Appointed himself chairman in 2018 via decree. Complete political control.",
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Erdogan directly (he chairs the board)",
                "independence_level": "none_erdogan_personal_vehicle",
                "note": "Erdogan made himself chairman in 2018. Fund holds Turkey's crown jewels (Turkish Airlines, Turk Telekom, Borsa Istanbul). Critics call it Erdogan's personal slush fund. No independent oversight.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Turkish Airlines (49.12% stake)", "value_usd": "~$8B", "confidence": "confirmed"},
                {"company": "Turk Telekom (6.68%)", "value_usd": "~$500M", "confidence": "confirmed"},
                {"company": "Halkbank (75.5%)", "value_usd": "~$2B", "confidence": "confirmed"},
                {"company": "Borsa Istanbul (73.6%)", "value_usd": "~$3B", "confidence": "confirmed"},
                {"company": "Ziraat Bank (100%)", "value_usd": "~$10B", "confidence": "estimated"},
                {"company": "Turkish Petroleum (TPAO, 100%)", "value_usd": "~$5B", "confidence": "estimated"},
                {"company": "Calik Holding JVs", "value_usd": "~$1B", "confidence": "rumored"},
                {"company": "ETI (Eti Maden, mining)", "value_usd": "~$3B", "confidence": "estimated"},
                {"company": "Various domestic industrial stakes", "value_usd": "~$5B", "confidence": "estimated"},
                {"company": "Istanbul Finance Center project", "value_usd": "~$3B", "confidence": "estimated"},
            ],
            "real_estate_holdings": [
                {"property": "Istanbul Finance Center (IFC)", "value_usd": "~$3B", "confidence": "estimated"},
                {"property": "Various Turkish land holdings", "value_usd": "~$2B", "confidence": "estimated"},
                {"property": "Turkish Airlines HQ campus", "value_usd": "~$1B", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "domestic_holding_company_not_real_swf",
                "note": "TWF is not a real sovereign wealth fund. It is a holding company for transferred state assets. No international investment strategy. Created to consolidate Erdogan's control over strategic assets and bypass parliamentary budget oversight.",
                "confidence": "derived",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~0-2%",
                "value_usd": "~$0-2B",
                "confidence": "estimated",
                "note": "Almost no international exposure. Entirely domestic asset holding company.",
            },
            "geopolitical_leverage": {
                "mechanism": "domestic_control_consolidation",
                "description": "TWF is primarily a domestic power consolidation tool, not a geopolitical instrument. Erdogan uses it to control banks, airlines, telecom, and the stock exchange without parliamentary oversight.",
                "examples": [
                    "Halkbank sanctions evasion case (Iran oil payments)",
                    "Ziraat Bank used for political lending",
                    "Borsa Istanbul ownership gives control over capital markets",
                ],
                "leverage_rating": "low_internationally_high_domestically",
                "confidence": "derived",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "very_low",
                "note": "Minimal public reporting. Board chaired by Erdogan. Exempt from normal audit requirements. Halkbank's role in Iran sanctions evasion (convicted in US court 2022) exposed some structures.",
                "confidence": "confirmed",
            },
        },
        # ── 15. NIGERIA NSIA ─────────────────────────────────────────
        {
            "id": "NSIA",
            "name": "Nigeria Sovereign Investment Authority",
            "country": "Nigeria",
            "aum_usd": "3B",
            "aum_confidence": "confirmed",
            "aum_trend": "up_slowly_from_low_base",
            "established": 2012,
            "key_personnel": [
                {
                    "name": "Aminu Umar-Sadiq",
                    "role": "Managing Director & CEO",
                    "since": 2020,
                    "confidence": "confirmed",
                },
            ],
            "political_connections": {
                "oversight": "Board includes Federal/State government reps, private sector",
                "independence_level": "medium",
                "note": "Established under Goodluck Jonathan. Survived political transitions. Three sub-funds: Stabilisation, Future Generations, Nigeria Infrastructure. Underfunded relative to oil revenues due to political spending pressures.",
                "confidence": "confirmed",
            },
            "top_equity_holdings": [
                {"company": "Nigerian domestic equities (small)", "value_usd": "~$200M", "confidence": "estimated"},
                {"company": "Global equity index funds", "value_usd": "~$500M", "confidence": "estimated"},
                {"company": "Nigerian fixed income", "value_usd": "~$300M", "confidence": "estimated"},
                {"company": "Global fixed income", "value_usd": "~$400M", "confidence": "estimated"},
                {"company": "Infrastructure projects (roads, bridges)", "value_usd": "~$800M", "confidence": "confirmed"},
                {"company": "Agriculture fund", "value_usd": "~$200M", "confidence": "estimated"},
                {"company": "Healthcare fund (post-COVID)", "value_usd": "~$100M", "confidence": "estimated"},
                {"company": "Real estate fund", "value_usd": "~$100M", "confidence": "estimated"},
                {"company": "Presidential Infrastructure Dev Fund", "value_usd": "~$300M", "confidence": "confirmed"},
                {"company": "Cash and short-term", "value_usd": "~$100M", "confidence": "estimated"},
            ],
            "real_estate_holdings": [
                {"property": "Nigerian commercial/industrial property", "value_usd": "~$100M", "confidence": "estimated"},
            ],
            "investment_style": {
                "approach": "domestic_development_focused",
                "note": "Smallest major SWF. Primarily focused on Nigerian infrastructure development and stabilisation. Limited international investment. Good governance intentions but politically constrained funding.",
                "confidence": "confirmed",
            },
            "us_market_exposure": {
                "pct_of_portfolio": "~15%",
                "value_usd": "~$450M",
                "confidence": "estimated",
            },
            "geopolitical_leverage": {
                "mechanism": "none",
                "description": "NSIA is too small for geopolitical leverage. Nigeria's leverage comes from oil production, population size, and regional influence, not sovereign wealth.",
                "leverage_rating": "none",
                "confidence": "confirmed",
            },
            "offshore_opaque_structures": {
                "transparency_rating": "medium_high",
                "note": "Publishes annual reports. Follows Santiago Principles. Relatively transparent for African SWF. Size limits complexity of structures.",
                "confidence": "confirmed",
            },
        },
    ],
    # ── CROSS-FUND ANALYSIS ──────────────────────────────────────────
    "cross_fund_analysis": {
        "total_aum_top_15": {
            "value_usd": "~8.2T",
            "confidence": "derived",
        },
        "us_market_total_exposure": {
            "value_usd": "~2.6-2.9T",
            "pct_of_us_market_cap": "~5-6% of total US equity market",
            "confidence": "estimated",
            "note": "SWFs collectively are among the largest holders of US equities. Norway alone holds ~1.5% of every listed US company.",
        },
        "transparency_ranking": [
            {"rank": 1, "fund": "GPFG (Norway)", "rating": "highest"},
            {"rank": 2, "fund": "Future Fund (Australia)", "rating": "high"},
            {"rank": 3, "fund": "KIC (South Korea)", "rating": "high"},
            {"rank": 4, "fund": "NSIA (Nigeria)", "rating": "medium_high"},
            {"rank": 5, "fund": "Temasek", "rating": "medium_high"},
            {"rank": 6, "fund": "Mubadala", "rating": "medium"},
            {"rank": 7, "fund": "HKMA", "rating": "medium"},
            {"rank": 8, "fund": "GIC", "rating": "medium_low"},
            {"rank": 9, "fund": "KIA (Kuwait)", "rating": "low"},
            {"rank": 10, "fund": "ADIA", "rating": "low"},
            {"rank": 11, "fund": "CIC (China)", "rating": "very_low"},
            {"rank": 12, "fund": "QIA (Qatar)", "rating": "very_low"},
            {"rank": 13, "fund": "PIF (Saudi)", "rating": "very_low"},
            {"rank": 14, "fund": "TWF (Turkey)", "rating": "very_low"},
            {"rank": 15, "fund": "NWF (Russia)", "rating": "none"},
        ],
        "geopolitical_leverage_ranking": [
            {"rank": 1, "fund": "CIC (China)", "rating": "very_high"},
            {"rank": 2, "fund": "PIF (Saudi)", "rating": "very_high"},
            {"rank": 3, "fund": "NWF (Russia)", "rating": "high_cautionary"},
            {"rank": 4, "fund": "QIA (Qatar)", "rating": "high"},
            {"rank": 5, "fund": "ADIA", "rating": "high"},
            {"rank": 6, "fund": "Mubadala", "rating": "high"},
            {"rank": 7, "fund": "HKMA", "rating": "medium_high"},
            {"rank": 8, "fund": "GPFG (Norway)", "rating": "medium_soft_power"},
            {"rank": 9, "fund": "KIA (Kuwait)", "rating": "medium"},
            {"rank": 10, "fund": "GIC", "rating": "medium"},
            {"rank": 11, "fund": "Temasek", "rating": "low_to_medium"},
            {"rank": 12, "fund": "TWF (Turkey)", "rating": "low_intl_high_domestic"},
            {"rank": 13, "fund": "Future Fund (Australia)", "rating": "none"},
            {"rank": 14, "fund": "KIC (South Korea)", "rating": "none"},
            {"rank": 15, "fund": "NSIA (Nigeria)", "rating": "none"},
        ],
        "family_control_map": {
            "al_nahyan_uae": {
                "funds_controlled": ["ADIA", "Mubadala"],
                "combined_aum": "~$1.29T",
                "key_figures": ["MBZ (President)", "Sheikh Tahnoun (ADIA Chair + NSA)", "Khaldoon Al Mubarak (Mubadala CEO)"],
                "confidence": "confirmed",
            },
            "al_thani_qatar": {
                "funds_controlled": ["QIA"],
                "combined_aum": "~$510B",
                "key_figures": ["Emir Tamim", "PM Al Thani (QIA Chair)"],
                "confidence": "confirmed",
            },
            "al_saud_saudi": {
                "funds_controlled": ["PIF"],
                "combined_aum": "~$930B",
                "key_figures": ["MBS (Chairman)"],
                "confidence": "confirmed",
            },
            "lee_family_singapore": {
                "funds_influenced": ["GIC", "Temasek"],
                "combined_aum": "~$1.15T",
                "key_figures": ["Lee Hsien Loong (GIC Chair)", "Ho Ching (Former Temasek CEO, his wife)"],
                "confidence": "confirmed",
            },
            "al_sabah_kuwait": {
                "funds_controlled": ["KIA"],
                "combined_aum": "~$920B",
                "confidence": "confirmed",
            },
        },
        "inter_fund_relationships": [
            {
                "type": "co_investment",
                "funds": ["ADIA", "GIC", "KIA"],
                "note": "Frequently co-invest in large PE and infrastructure deals",
                "confidence": "confirmed",
            },
            {
                "type": "competition",
                "funds": ["PIF", "QIA", "Mubadala"],
                "note": "Gulf SWFs compete for trophy assets, sports teams, and tech deals",
                "confidence": "confirmed",
            },
            {
                "type": "geopolitical_alignment",
                "funds": ["ADIA", "PIF", "Mubadala"],
                "note": "Saudi-UAE axis aligned on investments since 2017 reconciliation",
                "confidence": "derived",
            },
            {
                "type": "counter_alignment",
                "funds": ["QIA", "TWF"],
                "note": "Qatar-Turkey axis during 2017-2021 Gulf blockade. QIA supported Turkey's economy during 2018 lira crisis.",
                "confidence": "confirmed",
            },
        ],
        "systemic_risk_factors": [
            {
                "risk": "coordinated_us_treasury_selling",
                "actors": ["HKMA", "CIC", "ADIA", "GIC", "KIA"],
                "combined_ust_holdings": "~$400-600B estimated",
                "probability": "very_low",
                "impact": "catastrophic",
                "confidence": "estimated",
            },
            {
                "risk": "gulf_swf_retaliation_to_us_policy",
                "actors": ["PIF", "ADIA", "QIA", "KIA", "Mubadala"],
                "combined_us_exposure": "~$900B-1.1T",
                "trigger": "US policy on Israel, Iran, or energy",
                "probability": "very_low",
                "impact": "severe",
                "confidence": "estimated",
            },
            {
                "risk": "russia_reserve_freeze_contagion",
                "description": "Russia's frozen reserves causing other SWFs to diversify away from USD/Western assets",
                "actors_reducing_usd": ["CIC", "PIF", "QIA"],
                "confidence": "confirmed",
            },
        ],
    },
    # ── GRID TRADING SIGNALS ─────────────────────────────────────────
    "trading_signals": {
        "swf_flow_indicators": [
            {
                "signal": "PIF gaming accumulation",
                "tickers": ["NTDOY", "EA", "TTWO", "RBLX"],
                "direction": "bullish",
                "confidence": "confirmed",
                "note": "PIF systematically building gaming portfolio. May accumulate more.",
            },
            {
                "signal": "Gulf SWF AI/semiconductor interest",
                "tickers": ["NVDA", "MSFT", "GFS", "AMD"],
                "direction": "bullish",
                "confidence": "derived",
                "note": "Mubadala (GlobalFoundries), G42-MSFT deal, PIF AI ambitions.",
            },
            {
                "signal": "Norway ESG exclusion risk",
                "tickers": "monitor GPFG exclusion list",
                "direction": "bearish_for_excluded",
                "confidence": "confirmed",
                "note": "GPFG exclusion = signal for other ESG funds to follow. Watch ethic council recommendations.",
            },
            {
                "signal": "SWF real estate distress selling",
                "tickers": ["VNQ", "IYR", "commercial_reits"],
                "direction": "mixed",
                "confidence": "estimated",
                "note": "Some SWFs reducing office exposure post-COVID. Watch for distressed sales.",
            },
        ],
    },
}


def get_swf_intelligence():
    """Return the complete SWF intelligence dict for json.dumps()."""
    return SWF_INTELLIGENCE


def get_fund_by_id(fund_id: str) -> dict | None:
    """Retrieve a specific fund by its ID."""
    for fund in SWF_INTELLIGENCE["funds"]:
        if fund["id"] == fund_id:
            return fund
    return None


def get_all_fund_ids() -> list[str]:
    """Return list of all fund IDs."""
    return [f["id"] for f in SWF_INTELLIGENCE["funds"]]


def get_cross_fund_analysis() -> dict:
    """Return cross-fund analysis section."""
    return SWF_INTELLIGENCE["cross_fund_analysis"]


def get_trading_signals() -> dict:
    """Return SWF-derived trading signals."""
    return SWF_INTELLIGENCE["trading_signals"]


if __name__ == "__main__":
    import json
    print(json.dumps(SWF_INTELLIGENCE, indent=2, ensure_ascii=False))
